title: m0chan Blog - Info Sec, CTF & Hacking
author: m0chan
email: root@m0chan.co.uk
description: >-
  Info Sec, CTF & Hacking
show_excerpts: true

sass:
  sass_dir: _sass

# USE REMOTE THEME (not theme:)
remote_theme: thelehhman/plainwhite-jekyll@master

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-feed

plainwhite:
  name: m0chan
  tagline: Penetration Tester
  date_format: "%b %-d, %Y"
  sitemap: true
  social_links:
    twitter: m0chan98
    github: m0chan
    linkedIn: /in/aidan-preston
    rss: /feed.xml
